### PR TITLE
Update IAM sdk and mocks

### PR DESCRIPTION
**Pull request by MuweiHe**
mock generated with:

```
mocker --prefix "" --dst mock/api_invitations_iam_v2.go --pkg mock api_invitations_iam_v2.go InvitationsIamV2Api
```

### CODE REVIEW

**Comment by MuweiHe** [comment]
@linouk23 should i remove the devel and stag servers from the openapi file?

**Comment by linouk23** [comment]
that'd be great! you might want to remove them from `iam/v2/configuration.go` too and force push the changes as well

**Comment by linouk23** [comment]
thanks! could you squash these commits and force push the changes?

**Comment by MuweiHe** [comment]
> thanks! could you squash these commits into one commit and force push it to `origin/update-iam` branch?

Thanks! Just did

**Review by linouk23 — APPROVED** [review]

**Pull request merged**
