### PR TITLE
Update SDK for CMK API.

### PR DESCRIPTION
**Pull request by linouk23**
### What
This PR updates SDK for CMK API.

### CODE REVIEW

**Review by MuweiHe — COMMENTED** [review]
Looking good! Could you regenerate the mocks as well?

**Comment by linouk23** [comment]
That's a great idea! I did try to do it so I guess the interfaces stayed the same.

**Review by MuweiHe — APPROVED** [review]

**Comment by MuweiHe** [comment]
Could you do a release to include this pr? thanks!

**Comment by linouk23** [comment]
sure thing: https://github.com/confluentinc/ccloud-sdk-go-v2/releases/tag/cmk%2Fv0.6.0

**Pull request merged**
